'use strict';

// CJS shim for sites/blackroad/src/lib/quantumVisualization.js (ES module)
// Generated by jest.esm-to-cjs.cjs transform — referenced by moduleNameMapper in jest.config.js
const qv = require('../../sites/blackroad/src/lib/quantumVisualization.js');
module.exports = qv;
