name: "🧪 Commitlint"
name: lint-pr

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  commitlint:
    name: "🧪 commitlint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
<<<<        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@0825edbf07b4642d9b0dac510665547fd0dd5cf5 # v5.1.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
>>>>>>>+main
===
>>>>>>> origin/codex/pin-actions-to-full-length-commit-sha
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@e52b2b58b16eebceed991c671a22adce04e0e6ae # v5
        with:
          configFile: commitlint.config.js
