name: Marketing Monthly Report
on:
  schedule: [{ cron: "10 4 1 * *" }]
  workflow_dispatch:
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with: { node-version: '20' }
      - run: node scripts/mkt/report.ts
      - uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5
        with:
          commit_message: "chore(marketing): monthly report"
          file_pattern: "marketing/reports/MKT_*.md"
