name: SBOM
on:
  push:
    branches: [main]
    paths: ["apps/api/**", "release/**", ".github/workflows/sbom.yml"]
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: CycloneDX/gh-node-module-generatebom@a11e2e4d0b2ec8e03fdedfdeee0dce49e7f61d49 # v1
        with: { path: "apps/api", output: "bom.xml" }
      - uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4
        with: { name: sbom, path: bom.xml }
