name: secrets
on:
  pull_request:
  push:
jobs:
  ggshield:
    runs-on: ubuntu-latest
    env:
      GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5
      - run: pipx install ggshield
      - run: ggshield secret scan repo .
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@ff98106e4c7b2bc287b24eaf42907196329070c7 # v2
        with:
          args: detect --no-banner --redact --report-format sarif --report-path gitleaks.sarif
      - name: Upload report
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: always()
        with:
          name: gitleaks-report
          path: gitleaks.sarif
