name: tag-and-release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (x.y.z)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - run: git tag v${{ github.event.inputs.version }}
      - run: git push origin v${{ github.event.inputs.version }}
      - run: |
          echo "## v${{ github.event.inputs.version }}" > CHANGELOG.md
          git log --pretty=format:'* %s' $(git describe --tags --abbrev=0)..HEAD >> CHANGELOG.md
      - name: Publish GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v${{ github.event.inputs.version }}" \
            --title "v${{ github.event.inputs.version }}" \
            --notes-file CHANGELOG.md
      - uses: actions/create-release@0c0c5ff80a5c14fc7fdbb28b7b3d52d5e6a1b5d0 # v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: v${{ github.event.inputs.version }}
          body_path: CHANGELOG.md
