name: Update Branch On Label

on:
  pull_request_target:
    types:
      - labeled

permissions:
  contents: write
  pull-requests: write

jobs:
  update-branch:
    if: github.event.label.name == 'update-branch'
    runs-on: ubuntu-latest
    steps:
      - name: Update the pull request branch
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            await github.rest.pulls.updateBranch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });
      - name: Remove trigger label
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            try {
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                name: 'update-branch',
              });
            } catch (error) {
              if (error.status !== 404) {
                throw error;
              }
            }
